name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - run: ruff check && ruff format --check src/ bin/
    name: Lint

  test:
    runs-on: ubuntu-latest
    steps:
      - run: pytest tests/ -v
    needs: lint
    name: Tests